name: Build xr-voice-sdk in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/RDK*, 'feature/**', develop ]

permissions:
  contents: read

jobs:
  build-xr-voice-sdk-on-pr:
    name: Build xr-voice-sdk in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build dependencies
        run: |
          sh -x build_dependencies.sh
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}

      - name: cov build
        run: |
          sh -x cov_build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}
